AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    OpenSearchServiceDomain:
        Type: "AWS::OpenSearchService::Domain"
        Properties:
            DomainName: "photos-cf"
            EngineVersion: "OpenSearch_2.5"
            ClusterConfig:
                DedicatedMasterEnabled: false
                InstanceCount: 1
                InstanceType: "t3.small.search"
                ZoneAwarenessEnabled: false
                WarmEnabled: false
            SnapshotOptions: {}
            EncryptionAtRestOptions:
                Enabled: true
                KmsKeyId: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/62f5ae3b-2958-4c0b-bf86-f59831125100"
            NodeToNodeEncryptionOptions:
                Enabled: true
            AdvancedOptions:
                "indices.fielddata.cache.size": "20"
                "indices.query.bool.max_clause_count": "1024"
                override_main_response_version: "false"
                "rest.action.multi.allow_explicit_index": "true"
            EBSOptions:
                EBSEnabled: true
                VolumeType: "gp3"
                VolumeSize: 10
                Iops: 3000
                Throughput: 125
            CognitoOptions:
                Enabled: false
            DomainEndpointOptions:
                EnforceHTTPS: true
                TLSSecurityPolicy: "Policy-Min-TLS-1-0-2019-07"
                CustomEndpointEnabled: false

